from __future__ import annotations

from typing import Any


MARKET_DEFINITIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "WIN",
        "category": "result",
        "label": "Win",
        "subject": "team",
        "metric": "result",
        "operator": "win",
        "line": None,
        "period": "FT",
        "display_order": 10,
    },
    {
        "key": "DRAW",
        "category": "result",
        "label": "Draw",
        "subject": "match",
        "metric": "result",
        "operator": "draw",
        "line": None,
        "period": "FT",
        "display_order": 20,
    },
    {
        "key": "LOSS",
        "category": "result",
        "label": "Loss",
        "subject": "team",
        "metric": "result",
        "operator": "loss",
        "line": None,
        "period": "FT",
        "display_order": 30,
    },
    {
        "key": "UNBEATEN",
        "category": "result",
        "label": "Unbeaten",
        "subject": "team",
        "metric": "result",
        "operator": "custom",
        "line": None,
        "period": "FT",
        "display_order": 35,
    },
    {
        "key": "WINLESS",
        "category": "result",
        "label": "Winless",
        "subject": "team",
        "metric": "result",
        "operator": "custom",
        "line": None,
        "period": "FT",
        "display_order": 36,
    },
    {
        "key": "BTTS_YES",
        "category": "btts",
        "label": "BTTS",
        "subject": "match",
        "metric": "goals",
        "operator": "btts",
        "line": None,
        "period": "FT",
        "display_order": 40,
    },
    {
        "key": "MATCH_OVER_1_5_GOALS",
        "category": "goals",
        "label": "Over 1.5 Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 50,
    },
    {
        "key": "MATCH_OVER_2_5_GOALS",
        "category": "goals",
        "label": "Over 2.5 Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 60,
    },
    {
        "key": "MATCH_OVER_3_5_GOALS",
        "category": "goals",
        "label": "Over 3.5 Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 3.5,
        "period": "FT",
        "display_order": 70,
    },
    {
        "key": "MATCH_UNDER_2_5_GOALS",
        "category": "goals",
        "label": "Under 2.5 Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "under",
        "line": 2.5,
        "period": "FT",
        "display_order": 72,
    },
    {
        "key": "MATCH_UNDER_3_5_GOALS",
        "category": "goals",
        "label": "Under 3.5 Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "under",
        "line": 3.5,
        "period": "FT",
        "display_order": 74,
    },
    {
        "key": "TEAM_OVER_0_5_GOALS_FOR",
        "category": "goals",
        "label": "Over 0.5 Team Goals For",
        "subject": "team",
        "metric": "goals_for",
        "operator": "over",
        "line": 0.5,
        "period": "FT",
        "display_order": 80,
    },
    {
        "key": "TEAM_OVER_1_5_GOALS_FOR",
        "category": "goals",
        "label": "Over 1.5 Team Goals For",
        "subject": "team",
        "metric": "goals_for",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 90,
    },
    {
        "key": "TEAM_OVER_0_5_GOALS_AGAINST",
        "category": "goals",
        "label": "Over 0.5 Team Goals Against",
        "subject": "opponent",
        "metric": "goals_against",
        "operator": "over",
        "line": 0.5,
        "period": "FT",
        "display_order": 100,
    },
    {
        "key": "TEAM_OVER_1_5_GOALS_AGAINST",
        "category": "goals",
        "label": "Over 1.5 Team Goals Against",
        "subject": "opponent",
        "metric": "goals_against",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 110,
    },
    {
        "key": "MATCH_OVER_8_5_CORNERS",
        "category": "corners",
        "label": "Over 8.5 Match Corners",
        "subject": "match",
        "metric": "corners",
        "operator": "over",
        "line": 8.5,
        "period": "FT",
        "display_order": 200,
    },
    {
        "key": "MATCH_OVER_9_5_CORNERS",
        "category": "corners",
        "label": "Over 9.5 Match Corners",
        "subject": "match",
        "metric": "corners",
        "operator": "over",
        "line": 9.5,
        "period": "FT",
        "display_order": 210,
    },
    {
        "key": "MATCH_OVER_10_5_CORNERS",
        "category": "corners",
        "label": "Over 10.5 Match Corners",
        "subject": "match",
        "metric": "corners",
        "operator": "over",
        "line": 10.5,
        "period": "FT",
        "display_order": 220,
    },
    {
        "key": "TEAM_OVER_2_5_CORNERS_FOR",
        "category": "corners",
        "label": "Over 2.5 Team Corners For",
        "subject": "team",
        "metric": "corners_for",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 230,
    },
    {
        "key": "TEAM_OVER_3_5_CORNERS_FOR",
        "category": "corners",
        "label": "Over 3.5 Team Corners For",
        "subject": "team",
        "metric": "corners_for",
        "operator": "over",
        "line": 3.5,
        "period": "FT",
        "display_order": 240,
    },
    {
        "key": "TEAM_OVER_4_5_CORNERS_FOR",
        "category": "corners",
        "label": "Over 4.5 Team Corners For",
        "subject": "team",
        "metric": "corners_for",
        "operator": "over",
        "line": 4.5,
        "period": "FT",
        "display_order": 250,
    },
    {
        "key": "TEAM_OVER_5_5_CORNERS_FOR",
        "category": "corners",
        "label": "Over 5.5 Team Corners For",
        "subject": "team",
        "metric": "corners_for",
        "operator": "over",
        "line": 5.5,
        "period": "FT",
        "display_order": 255,
    },
    {
        "key": "TEAM_OVER_2_5_CORNERS_AGAINST",
        "category": "corners",
        "label": "Over 2.5 Team Corners Against",
        "subject": "opponent",
        "metric": "corners_against",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 260,
    },
    {
        "key": "TEAM_OVER_3_5_CORNERS_AGAINST",
        "category": "corners",
        "label": "Over 3.5 Team Corners Against",
        "subject": "opponent",
        "metric": "corners_against",
        "operator": "over",
        "line": 3.5,
        "period": "FT",
        "display_order": 265,
    },
    {
        "key": "MOST_CORNERS",
        "category": "corners",
        "label": "Most Corners",
        "subject": "team",
        "metric": "corners",
        "operator": "most",
        "line": None,
        "period": "FT",
        "display_order": 270,
    },
    {
        "key": "MATCH_OVER_1_5_CARDS",
        "category": "cards",
        "label": "Over 1.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 295,
    },
    {
        "key": "MATCH_OVER_2_5_CARDS",
        "category": "cards",
        "label": "Over 2.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 300,
    },
    {
        "key": "MATCH_OVER_3_5_CARDS",
        "category": "cards",
        "label": "Over 3.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 3.5,
        "period": "FT",
        "display_order": 310,
    },
    {
        "key": "MATCH_OVER_4_5_CARDS",
        "category": "cards",
        "label": "Over 4.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 4.5,
        "period": "FT",
        "display_order": 320,
    },
    {
        "key": "MATCH_OVER_5_5_CARDS",
        "category": "cards",
        "label": "Over 5.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 5.5,
        "period": "FT",
        "display_order": 325,
    },
    {
        "key": "MATCH_OVER_6_5_CARDS",
        "category": "cards",
        "label": "Over 6.5 Total Cards",
        "subject": "match",
        "metric": "cards",
        "operator": "over",
        "line": 6.5,
        "period": "FT",
        "display_order": 326,
    },
    {
        "key": "TEAM_OVER_1_5_CARDS_FOR",
        "category": "cards",
        "label": "Over 1.5 Team Cards For",
        "subject": "team",
        "metric": "cards_for",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 330,
    },
    {
        "key": "TEAM_OVER_2_5_CARDS_FOR",
        "category": "cards",
        "label": "Over 2.5 Team Cards For",
        "subject": "team",
        "metric": "cards_for",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 335,
    },
    {
        "key": "OPPONENT_OVER_1_5_CARDS",
        "category": "cards",
        "label": "Over 1.5 Team Cards Against",
        "subject": "opponent",
        "metric": "cards_against",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 340,
    },
    {
        "key": "OPPONENT_OVER_2_5_CARDS",
        "category": "cards",
        "label": "Over 2.5 Team Cards Against",
        "subject": "opponent",
        "metric": "cards_against",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 345,
    },
    {
        "key": "EACH_TEAM_OVER_0_5_CARDS",
        "category": "cards",
        "label": "Each Team Over 0.5 Cards",
        "subject": "each_team",
        "metric": "cards",
        "operator": "over",
        "line": 0.5,
        "period": "FT",
        "display_order": 350,
    },
    {
        "key": "EACH_TEAM_OVER_1_5_CARDS",
        "category": "cards",
        "label": "Each Team Over 1.5 Cards",
        "subject": "each_team",
        "metric": "cards",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 360,
    },
    {
        "key": "EACH_TEAM_OVER_2_5_CARDS",
        "category": "cards",
        "label": "Each Team Over 2.5 Cards",
        "subject": "each_team",
        "metric": "cards",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 370,
    },
    {
        "key": "MATCH_OVER_15_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 15 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 15,
        "period": "FT",
        "display_order": 390,
    },
    {
        "key": "MATCH_OVER_25_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 25 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 25,
        "period": "FT",
        "display_order": 400,
    },
    {
        "key": "MATCH_OVER_35_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 35 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 35,
        "period": "FT",
        "display_order": 410,
    },
    {
        "key": "MATCH_OVER_45_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 45 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 45,
        "period": "FT",
        "display_order": 420,
    },
    {
        "key": "MATCH_OVER_55_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 55 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 55,
        "period": "FT",
        "display_order": 425,
    },
    {
        "key": "MATCH_OVER_65_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Over 65 Booking Points",
        "subject": "match",
        "metric": "booking_points",
        "operator": "over",
        "line": 65,
        "period": "FT",
        "display_order": 426,
    },
    {
        "key": "TEAM_OVER_15_BOOKING_POINTS_FOR",
        "category": "booking_points",
        "label": "Over 15 Team Booking Points For",
        "subject": "team",
        "metric": "booking_points_for",
        "operator": "over",
        "line": 15,
        "period": "FT",
        "display_order": 430,
    },
    {
        "key": "TEAM_OVER_25_BOOKING_POINTS_FOR",
        "category": "booking_points",
        "label": "Over 25 Team Booking Points For",
        "subject": "team",
        "metric": "booking_points_for",
        "operator": "over",
        "line": 25,
        "period": "FT",
        "display_order": 440,
    },
    {
        "key": "TEAM_OVER_15_BOOKING_POINTS_AGAINST",
        "category": "booking_points",
        "label": "Over 15 Team Booking Points Against",
        "subject": "opponent",
        "metric": "booking_points_against",
        "operator": "over",
        "line": 15,
        "period": "FT",
        "display_order": 450,
    },
    {
        "key": "TEAM_OVER_25_BOOKING_POINTS_AGAINST",
        "category": "booking_points",
        "label": "Over 25 Team Booking Points Against",
        "subject": "opponent",
        "metric": "booking_points_against",
        "operator": "over",
        "line": 25,
        "period": "FT",
        "display_order": 455,
    },
    {
        "key": "EACH_TEAM_OVER_5_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Each Team Over 5 Booking Points",
        "subject": "each_team",
        "metric": "booking_points",
        "operator": "over",
        "line": 5,
        "period": "FT",
        "display_order": 458,
    },
    {
        "key": "EACH_TEAM_OVER_15_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Each Team Over 15 Booking Points",
        "subject": "each_team",
        "metric": "booking_points",
        "operator": "over",
        "line": 15,
        "period": "FT",
        "display_order": 460,
    },
    {
        "key": "EACH_TEAM_OVER_25_BOOKING_POINTS",
        "category": "booking_points",
        "label": "Each Team Over 25 Booking Points",
        "subject": "each_team",
        "metric": "booking_points",
        "operator": "over",
        "line": 25,
        "period": "FT",
        "display_order": 462,
    },
    {
        "key": "MATCH_OVER_0_5_1H_GOALS",
        "category": "half",
        "label": "Over 0.5 1st Half Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 0.5,
        "period": "1H",
        "display_order": 500,
    },
    {
        "key": "MATCH_OVER_1_5_1H_GOALS",
        "category": "half",
        "label": "Over 1.5 1st Half Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 1.5,
        "period": "1H",
        "display_order": 510,
    },
    {
        "key": "TEAM_OVER_0_5_1H_GOALS_FOR",
        "category": "half",
        "label": "Over 0.5 1st Half Goals For",
        "subject": "team",
        "metric": "goals_for",
        "operator": "over",
        "line": 0.5,
        "period": "1H",
        "display_order": 520,
    },
    {
        "key": "TEAM_OVER_0_5_1H_GOALS_AGAINST",
        "category": "half",
        "label": "Over 0.5 1st Half Goals Against",
        "subject": "opponent",
        "metric": "goals_against",
        "operator": "over",
        "line": 0.5,
        "period": "1H",
        "display_order": 530,
    },
    {
        "key": "MATCH_OVER_0_5_2H_GOALS",
        "category": "half",
        "label": "Over 0.5 2nd Half Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 0.5,
        "period": "2H",
        "display_order": 600,
    },
    {
        "key": "MATCH_OVER_1_5_2H_GOALS",
        "category": "half",
        "label": "Over 1.5 2nd Half Goals",
        "subject": "match",
        "metric": "goals",
        "operator": "over",
        "line": 1.5,
        "period": "2H",
        "display_order": 610,
    },
    {
        "key": "TEAM_OVER_0_5_2H_GOALS_FOR",
        "category": "half",
        "label": "Over 0.5 2nd Half Goals For",
        "subject": "team",
        "metric": "goals_for",
        "operator": "over",
        "line": 0.5,
        "period": "2H",
        "display_order": 620,
    },
    {
        "key": "TEAM_OVER_0_5_2H_GOALS_AGAINST",
        "category": "half",
        "label": "Over 0.5 2nd Half Goals Against",
        "subject": "opponent",
        "metric": "goals_against",
        "operator": "over",
        "line": 0.5,
        "period": "2H",
        "display_order": 630,
    },
    {
        "key": "TEAM_OVER_10_5_SHOTS_FOR",
        "category": "shots",
        "label": "Over 10.5 Team Shots For",
        "subject": "team",
        "metric": "shots_for",
        "operator": "over",
        "line": 10.5,
        "period": "FT",
        "display_order": 700,
    },
    {
        "key": "TEAM_OVER_3_5_SHOTS_ON_TARGET_FOR",
        "category": "shots",
        "label": "Over 3.5 Team Shots On Target For",
        "subject": "team",
        "metric": "shots_on_target",
        "operator": "over",
        "line": 3.5,
        "period": "FT",
        "display_order": 710,
    },
    {
        "key": "MATCH_OVER_20_5_FOULS",
        "category": "fouls",
        "label": "Over 20.5 Match Fouls",
        "subject": "match",
        "metric": "fouls",
        "operator": "over",
        "line": 20.5,
        "period": "FT",
        "display_order": 800,
    },
    {
        "key": "TEAM_OVER_10_5_FOULS_COMMITTED",
        "category": "fouls",
        "label": "Over 10.5 Team Fouls Committed",
        "subject": "team",
        "metric": "fouls_committed",
        "operator": "over",
        "line": 10.5,
        "period": "FT",
        "display_order": 810,
    },
    {
        "key": "MATCH_OVER_2_5_OFFSIDES",
        "category": "offsides",
        "label": "Over 2.5 Match Offsides",
        "subject": "match",
        "metric": "offsides",
        "operator": "over",
        "line": 2.5,
        "period": "FT",
        "display_order": 900,
    },
    {
        "key": "TEAM_OVER_1_5_OFFSIDES_FOR",
        "category": "offsides",
        "label": "Over 1.5 Team Offsides For",
        "subject": "team",
        "metric": "offsides_for",
        "operator": "over",
        "line": 1.5,
        "period": "FT",
        "display_order": 910,
    },
)


def ensure_market_definitions(repository) -> None:
    repository.upsert_market_definitions(list(MARKET_DEFINITIONS))
